Actuator states
CarletonURocketry/hybrid-engine-ui pull request #18
Opened 2024-11-02 17:00 UTC by jackricketts

Added actuator states to the ui, removed the stop/start sim button, and made more room for the output log. More design stuff can be done (ex. making closed/open text red/green respectively, maybe adding unique labels if valves aren't in use) but it is good for now.

2024-11-02 17:26 UTC, jackricketts commented
Not sure if the if statement is correct, but I changed it from instanceof for now

2024-11-04 22:22 UTC, EliasJRH requested changes

2024-11-04 22:22 UTC, EliasJRH commented on widget.py
>              self.plot_point(header, message)
I don't think this field exists on the PacketHeader class. Also, can we put this in an if else so we're not always calling plot point.

2024-11-04 22:22 UTC, EliasJRH commented on widget.py
> +        """
Did you mean to set the background color to red and to leave this here? It might be nice to have the background color be red initially

2024-11-06 04:26 UTC, EliasJRH approved these changes
Good work!

2024-11-06 04:26 UTC, merged